# Generated by Django 4.1 on 2024-12-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='followed_startups',
            field=models.ManyToManyField(blank=True, related_name='followers', to='profiles.startupprofile'),
        ),
    ]
