# Generated by Django 4.2.16 on 2025-01-21 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_startupprofile_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedStratups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.investorprofile')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.startupprofile')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='viewedstratups',
            constraint=models.UniqueConstraint(condition=models.Q(('viewed_at__date', django.db.models.functions.datetime.TruncDate('viewed_at'))), fields=('investor', 'startup'), name='one_view_per_day'),
        ),
    ]
