# Generated by Django 4.2.16 on 2025-01-22 14:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_investorprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
