# Generated by Django 4.2.16 on 2025-01-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_startupprofile_is_public'),
        ('notifications', '0002_notificationcategory_notificationmethod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartUpNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='profiles.investorprofile')),
                ('notification_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationcategory')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='profiles.startupprofile')),
            ],
            options={
                'verbose_name': 'Startup Notification',
                'verbose_name_plural': 'Startup Notifications',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='startupnotification',
            constraint=models.UniqueConstraint(fields=('notification_category', 'investor', 'startup'), name='unique_notification'),
        ),
    ]
