# Generated by Django 4.2.16 on 2025-01-10 19:12

from django.db import migrations
from notifications.models import NotificationCategory, NotificationMethod
from users.serializers import create_default_notification_preferences
from django.contrib.auth import get_user_model


def add_notifications(apps, schema_editor):
    notification_categories = [
        NotificationCategory(name="follow", description="A new investor is following your startup."),
        NotificationCategory(name="profile_update", description="A startup has updated its profile."),
        NotificationCategory(name="new_project", description="A startup has added a new project."),
    ]
    NotificationCategory.objects.bulk_create(notification_categories)

    notification_methods = [
        NotificationMethod(name="email", description="Send notification through email."),
        NotificationMethod(name="in_app", description="Send notification within the app."),
    ]
    NotificationMethod.objects.bulk_create(notification_methods)


def add_default_user_preferences(apps, schema_editor):
    CustomUser = get_user_model()
    
    for user in CustomUser.objects.all():
        create_default_notification_preferences(user)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_startupnotification_and_more'),
    ]

    operations = [
         migrations.RunPython(add_notifications),
         migrations.RunPython(add_default_user_preferences, migrations.RunPython.noop),
    ]
