apiVersion: v1
kind: PersistentVolume
metadata:
  name: forum-db-pv
  labels:
    app: forum-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/postgresql
