apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forum-db-pvc
  labels:
    app: forum-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
