# Generated by Django 4.2 on 2025-01-06 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_startupprofile_is_public'),
        ('projects', '0004_alter_description_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='profiles.investorprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='projects.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(check=models.Q(('share__gt', 0)), name='share_positive', violation_error_message='Share must be greater than zero.'),
        ),
    ]
