# Generated by Django 4.1 on 2024-12-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_description_description'),
        ('projects', '0004_alter_description_description'),
    ]

    operations = [
    ]
